# Plataforma Matemática
# http://edurondon.tplinkdns.com:8031/
#teste
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: ${SECRET_KEY}
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"